[workspace]
resolver = "2"
members = ["steel", "steel-registry", "steel-utils", "steel-world"]

[workspace.package]
version = "0.0.0"
edition = "2024"


[workspace.dependencies]
tokio = { version = "1.48", features = [
    "macros",
    "net",
    "rt-multi-thread",
    "sync",
    "io-std",
    "signal",
    "fs",
    "io-util",
    "time",
] }
scc = { version = "3.3.2" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
