[package]
name = "steel-registry"
version.workspace = true
edition.workspace = true
build = "build/build.rs"

[dependencies]
steel-utils = { path = "../steel-utils" }

[build-dependencies]
proc-macro2.workspace = true
quote.workspace = true
serde_json.workspace = true
serde.workspace = true
steel-utils = { path = "../steel-utils" }
heck = "0.5.0"
