[package]
name = "steel-world"
version.workspace = true
edition.workspace = true

[dependencies]
steel-utils = { path = "../steel-utils" }
steel-protocol = { path = "../steel-protocol" }
scc.workspace = true
uuid.workspace = true
serde.workspace = true
